definiciones = {
    "acera": "Parte de una vía destinada al uso de peatones.",
    "adelantamiento": "Maniobra efectuada por el costado izquierdo del eje de la calzada, mediante la cual un vehículo se sitúa delante de otro u otros que le antecedían.",
    "aparato_sonoro": "Mecanismo de tipo manual o eléctrico que emite sonido.",
    "avenida_o_calle": "Vía urbana destinada a la circulación de los peatones, de los vehículos y de los animales.",
    "berma": "Faja lateral, pavimentada o no, adyacente a la calzada de un camino.",
    "bicicleta": "Ciclo de dos ruedas cuyos pedales transmiten el movimiento a la rueda trasera, generalmente por medio de un plato, un piñón y una cadena.",
    "calzada": "Parte de una vía destinada al uso de vehículos y animales.",
    "camino": "Vía rural destinada al uso de peatones, vehículos y animales.",
    "ciclo": "Vehículo no motorizado de una o más ruedas, propulsado por una o más personas. También incluye vehículos con motor auxiliar eléctrico de hasta 0,25 kW con asistencia limitada a 25 km/h.",
    "ciclovia": "Espacio destinado al uso exclusivo de bicicletas y otros ciclos, que puede estar segregada física o visualmente.",
    "conductor": "Persona que conduce, maneja o tiene control de un vehículo motorizado, animal de tiro o arreo, o remolque en la vía pública.",
    "cruce": "Unión de una calle o camino con otros, aunque no los atraviese. Abarca todo su ancho.",
    "cruce_de_ferrocarriles": "Intersección de una calle o camino con una vía férrea con tráfico regular de trenes.",
    "cruce_regulado": "Cruce con semáforo en funcionamiento (no intermitente) o Carabinero dirigiendo el tránsito.",
    "cuneta": "En calles, ángulo entre calzada y acera; en caminos, foso lateral de poca profundidad.",
    "chasis": "Armazón del vehículo, excluye carrocería y accesorios para conductor, pasajeros o carga.",
    "demarcacion": "Símbolo, palabra o marca sobre la calzada que guía el tránsito de vehículos y peatones.",
    "derecho_preferente_de_paso": "Prerrogativa de un peatón o conductor para proseguir su marcha.",
    "detencion": "Paralización breve por señales o para dejar/pickear pasajeros, mientras dure la maniobra.",
    "eje_de_calzada": "Línea longitudinal real o imaginaria que divide la calzada en sentidos opuestos.",
    "esquina": "El vértice del ángulo que forman las líneas de edificación o deslinde convergentes, según sea el caso.",
    "estacionamiento": "Lugar permitido por la autoridad para estacionar.",
    "estacionar": "Paralizar un vehículo en la vía pública con o sin el conductor, por un período mayor que el necesario para dejar o recibir pasajeros.",
    "guarda_cruzada": "Encargado de la vigilancia de un cruce de ferrocarril.",
    "homologacion": "Certificación de que un modelo de vehículo cumple las normas técnicas vigentes del Ministerio de Transportes y Telecomunicaciones.",
    "interseccion": "Área común de calzadas que se cruzan o convergen.",
    "licencia_de_conductor": "Documento otorgado por la autoridad que habilita a conducir vehículos motorizados o de tracción animal.",
    "linea_de_detencion_de_veh": (
        "Línea transversal a la calzada antes de una intersección o paso peatonal. "
        "En cruces regulados: a no menos de 1 metro. En otros cruces: justo antes del cruce."
    ),
    "linea_detencion_ad": "Línea demarcada antes de un cruce regulado que determina la zona de espera de ciclos o motocicletas.",
    "linea_de_edificacion": "Deslinde entre la propiedad y la acera.",
    "locomocion_colectiva": "Servicio remunerado de transporte público de personas.",
    "luz_baja": "Luz que permite ver obstáculos a 50 metros. Haz luminoso paralelo a la calzada.",
    "luz_alta": "Luz que permite ver obstáculos a 150 metros. Haz potente paralelo a la calzada.",
    "luz_de_estacionamiento": "Luz continua o intermitente que identifica un vehículo estacionado.",
    "padron": "Documento de la autoridad que identifica al vehículo y su dueño para circular legalmente.",
    "paso_para_peatones": "Senda señalizada para el cruce seguro de peatones.",
    "pista_de_circulacion": "Faja demarcada o imaginaria destinada al tránsito de una fila de vehículos.",
    "pista_de_uso_exclusivo": "Espacio de la calzada reservado para ciertos vehículos autorizados.",
    "placa_patente": "Distintivo oficial que individualiza al vehículo.",
    "semaforo": "Dispositivo luminoso que regula la circulación de vehículos y peatones.",
    "senal_de_transito": "Dispositivos oficiales permanentes o variables que regulan o encauzan el tránsito.",
    "sobrepasar": "Maniobra de adelantamiento sin traspasar el eje de la calzada.",
    "taxi": "Automóvil destinado al transporte público de personas.",
    "transito": "Desplazamiento de peatones, animales o vehículos por vías públicas.",
    "triciclo_motorizado": "Vehículo de tres ruedas para carga menor a 300 kg.",
    "vehiculo": (
        "Medio de transporte motorizado o no. No incluye ayudas técnicas como sillas de ruedas o coches de bebé."
    ),
    "vehiculo_de_emergencia": "Pertenece a instituciones autorizadas como Carabineros, Bomberos o ambulancias fiscales.",
    "vehiculo_de_locomocion": "Vehículo público para transporte de personas, excluyendo taxis no colectivos.",
    "vehiculo_escolar": "Vehículo diseñado para transportar más de siete escolares desde/hacia el colegio.",
    "vehiculo_tranvia": "Vehículo urbano de pasajeros que circula exclusivamente sobre rieles.",
    "via": "Calle, camino u otro lugar destinado al tránsito.",
    "via_de_transito_restringido": "Vía donde solo se puede acceder bajo condiciones específicas definidas por la autoridad.",
    "zona_de_espera_especial": "Área demarcada para que ciclos o motos inicien la marcha antes que otros vehículos.",
    "zona_de_transito_calmado": (
        "Áreas urbanas donde se reduce la velocidad máxima a 40, 30 o 20 km/h mediante diseño vial."
    ),
    "via_exclusiva": "Calzada señalizada de uso exclusivo para ciertos vehículos.",
    "zona_rural": "Área geográfica fuera de los límites urbanos.",
    "zona_urbana": "Área cuyo límite está determinado por la municipalidad para efectos legales.",
}
